### ISSUE TITLE
Budget calculator

### ISSUE THREAD

**Issue by mpagels** [mpagels/budget-splitter#6]
As a user
I want that spends set off against
so that I can see, how much the other owes the other.

# Description
Martin has paid 70€ for gasoline. This should be split. Jana owes Martin €35 right now.
Jana has paid 70€ for Dinner for the whole Family. But, Martins dinner was €40, Janas Dinner was €20, the child's dinner was € 10. Martin has to pay back the whole 40 Euro and the child's costs are split, so 5 Euro.
Martin owes Jana now €45. Minus the €35 Martin owes 10 Euro.

Acceptance criterias
- [x] it should display the whole amount of spend in the list on the dashboard
- [x] it should display the amount that is owed or that needs to be repaid for that spend item
- [x] at the bottom it should calculate the current balance situation

### task
- [x] write calculator algorithmus
